"""**Rover** is an automated report maker that creates Latex reports from XML data generated by TargetLynx.

An analyst exports data produced by a waters HPLC/UV set-up from TargetLynx as an XML file. This XML file is opened
up in excel, which produces a schema. This file is saved in the xml_data_files directory.

Once this is done, the analyst runs GUI/RoverGUI. They select the data file.

**Pre_Generate** will manipulate the data in the following ways:

1. organizing data into blanks, standards, samples, and dilutions.
2. Finding the best blank and standard to report with the sample data.
3. Swapping out out of calibration values with corresponding values from sample dilutions.
4. Finding the correct header file (customer information) to go with the data, parsing it, and attaching it to the data.
5. rounding raw values to an appropriate amount of significant figures.
6. convert the analytical concentration to a percentage concentration.a

Once Pre_Generate is finished, it will present the batch information in the **GUI**. The analyst will have the opportunity
on this page to do the following:

1. Change incorrectly parsed header and sample name information.
2. Review the best blank and the best standard, review the raw data produced by pre_generate.
3. Select unit type, deluxe/basic reporting, single/multiple samples per page. Add unit masses/density where relevant.

Once header information has been verified, the data reviewed, and options are selected, the analyst will hit the
"generate batch" button at the bottom of the GUI batch window screen. **Post_Generate** will assemble the relevant reports.

If all goes well, Latex files will be generated in the 'reports' directory. These latex files can be
converted to PDF form by any latex writing/editing program - TeXnicCenter is one example, and is an excellent program.
These latex files can be directly edited and provide one last place to modify information on the reports - this is
the only place where an analyst can manipulate the actual sample data. This means that no human interacts with any piece
of data other than customer information throughout the report generating process. Any error in the data can only come
from the program itself, or have been generated prior to producing the XML file for the Rover program.

Rover comes with **documentation** in the docs folder. Opening index.html in a browser will give you access to these."""